version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: jobportal-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: jobportal-server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env.docker
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: jobportal-client
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    env_file:
      - ./client/.env.docker
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mongo-data:
 
